version: '3'

services:
  frontend:
    image: front
    container_name: NDI_frontend
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - app_network
  backend:
    image: back
    container_name: NDI_backend
    build: 
      context: backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_URI=mongodb://mongodb:27017/
      - MONGO_DB=NDI
    volumes:
      - ./backend/src:/app/src
    depends_on:
      - mongodb
    networks:
      - app_network

  mongodb:
    container_name: NDI-mongo
    image: mongo
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - app_network
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  app_network: