# Start with a base image containing Java runtime and Maven
FROM maven:3.8.4-openjdk-17
WORKDIR /app
COPY ./pom.xml ./pom.xml
# Resolve all dependencies
RUN mvn dependency:go-offline -B
COPY ./src ./src
RUN mvn clean package -DskipTests
# Make port 8080 available to the world outside this container
EXPOSE 8080
# Run the jar file 
ENTRYPOINT ["java","-jar","target/backend-0.0.1-SNAPSHOT.jar"]