# Start with a base image containing Java runtime and Maven
FROM maven:3.8.4-openjdk-17
WORKDIR /app
COPY ./pom.xml ./pom.xml
# Resolve all dependencies
RUN mvn dependency:go-offline -B
COPY ./src ./src
RUN mvn clean package -DskipTests
# Start with a base image containing Java runtime and Maven
FROM maven:3.8.4-openjdk-17

# Copy the jar from the build stage
COPY --from=build /app/target/*.jar /app.jar

# Run the jar file 
ENTRYPOINT ["java","-jar","/app.jar"]
